kind: Service
apiVersion: v1
metadata:
  name: dataplane-main
  namespace: default
  labels:
    app: dataplane-main
spec:
  ports:
    - name: tcp
      protocol: TCP
      #      port = port connected to ingress
      port: 9000
      # targetPort = port on container
      targetPort: 9000
  selector:
    app: dataplane-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataplane-main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataplane-main
  template:
    metadata:
      labels:
        app: dataplane-main
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: container
          image: dataplane/dataplane:latest
          imagePullPolicy: Always
          command:
            - "./dataplane"
          ports:
            - containerPort: 9000
          env:
            - name: DP_CODE_FOLDER
              value: "/dataplane/code-files/"
            - name: DP_DB_HOST
              value: timescaledb-service
            - name: DP_DB_USER
              value: postgres
            - name: secret_db_pwd 
              value: "Hello123!"
            - name: DP_DB_SSL
              value: "disable"
            - name: DP_DB_PORT
              value: "5432"
            - name: DP_DB_DATABASE
              value: "dataplane"
            - name: DP_DATABASE
              value: "timescaledb"
            - name: DP_PORT
              value: "9000"
            - name: DP_NATS
              value: "nats://nats-0.nats.default.svc:4222, nats://nats-1.nats.default.svc:4222, nats-3.nats.default.svc:4222"
            - name: DP_MODE
              value: "development"
            - name: DP_DEBUG
              value: "true"
            - name: DP_DB_DEBUG
              value: "false"
            - name: DP_MQ_DEBUG
              value: "false"
            - name: DP_METRIC_DEBUG
              value: "false"
            - name: DP_SCHEDULER_DEBUG
              value: "true"
            - name: DP_CLEANTASKS_DAYS
              value: "60"
            - name: DP_REMOVELOGS_DAYS
              value: "60"
            - name: DP_CODE_FILE_STORAGE
              value: "Database"
            - name: DP_DFS_CODE_FOLDER
              value: "/dataplane/dfs-code-files/"