kind: Service
apiVersion: v1
metadata:
  name: dataplane-main
  namespace: default
  labels:
    app: dataplane-main
spec:
  ports:
    - name: tcp
      protocol: TCP
      #      port = port connected to ingress
      port: 9000
      # targetPort = port on container
      targetPort: 9000
  selector:
    app: dataplane-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataplane-main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataplane-main
  template:
    metadata:
      labels:
        app: dataplane-main
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: container
          image: dataplane/dataplane-main:latest
          command:
            - "./dataplane"
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "200Mi"
              cpu: "0.2"
            requests:
              memory: "100Mi"
              cpu: "0.1"
          env:
            - name: DP_CODE_FOLDER
              value: "/appdev/code-files/"
            - name: secret_db_host
              value: timescaledb-service
            - name: secret_db_user 
              value: postgres
            - name: secret_db_pwd 
              value: "Hello123!"
            - name: secret_db_ssl 
              value: "disable"
            - name: secret_db_port
              value: "5432"
            - name: secret_db_database
              value: "dataplane"
            - name: secret_jwt_secret
              value: "117943e8-9d43-49ac-aa4d-9c64004c8992"
            - name: secret_encryption_key
              value: "%WKrsNJTT*gM&9iX*iXXXiXrURdK2QTB"
            - name: database
              value: "timescaledb"
            - name: DP_PORT
              value: "9000"
            - name: DP_NATS
              value: "nats://nats-0.nats.default.svc:4222, nats://nats-1.nats.default.svc:4222, nats-3.nats.default.svc:4222"
            - name: DP_MODE
              value: "development"
            - name: DP_DEBUG
              value: "false"
            - name: DP_DB_DEBUG
              value: "false"
            - name: DP_MQ_DEBUG
              value: "false"
            - name: DP_METRIC_DEBUG
              value: "false"
            - name: DP_SCHEDULER_DEBUG
              value: "true"
            - name: DP_WORKER_HEARTBEAT_SECONDS
              value: "1"
            - name: DP_WORKER_GROUP
              value: "python_1"
      # vm, container, kubernetes
            - name: DP_WORKER_TYPE
              value: "vm"
            - name: DP_WORKER_LB
              value: "roundrobin"
            - name: DP_WORKER_ENV
              value: "Development"
            - name: DP_CLEANTASKS_DAYS
              value: "60"
            - name: DP_REMOVELOGS_DAYS
              value: "60"