apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataplane-worker-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataplane-worker-prod
  template:
    metadata:
      labels:
        app: dataplane-worker-prod
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
      volumes:
        - name: dp-code-cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 250Mi
      containers:
        - name: container
          image: dataplane/dataplane-worker-python:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/dataplane/dfs-code-files"
              name: dp-code-cache-volume
              subPath: dfs-code-files
          command:
            - "./dataplane-worker"
          ports:
            - containerPort: 9005
          env:
            - name: DP_CODE_FOLDER
              value: "/dataplane/code-files/"
            - name: secret_db_host
              value: timescaledb-service
            - name: secret_db_user 
              value: postgres
            - name: secret_db_pwd 
              value: "Hello123!"
            - name: secret_db_ssl 
              value: "disable"
            - name: secret_db_port
              value: "5432"
            - name: secret_db_database
              value: "dataplane"
            - name: secret_jwt_secret
              value: "117943e8-9d43-49ac-aa4d-9c64004c8992"
            - name: secret_encryption_key
              value: "%WKrsNJTT*gM&9iX*iXXXiXrURdK2QTB"
            - name: database
              value: "timescaledb"
            - name: DP_PORT
              value: "9000"
            - name: DP_NATS
              value: "nats://nats-0.nats.default.svc:4222, nats://nats-1.nats.default.svc:4222, nats-3.nats.default.svc:4222"
            - name: DP_MODE
              value: "development"
            - name: DP_DEBUG
              value: "false"
            - name: DP_DB_DEBUG
              value: "false"
            - name: DP_MQ_DEBUG
              value: "false"
            - name: DP_METRIC_DEBUG
              value: "false"
            - name: DP_SCHEDULER_DEBUG
              value: "true"
            - name: DP_WORKER_HEARTBEAT_SECONDS
              value: "1"
            - name: DP_WORKER_GROUP
              value: "python_prod"
            # vm, container, kubernetes
            - name: DP_WORKER_TYPE
              value: "vm"
            - name: DP_WORKER_LB
              value: "roundrobin"
            - name: DP_WORKER_ENV
              value: "Production"
            - name: DP_WORKER_CMD
              value: "/bin/sh"
            - name: DP_WORKER_PORT
              value: "9005"
            - name: DP_WORKER_LANGUAGES
              value: "Python"
            - name: DP_WORKER_LOAD_PACKAGES
              value: "Python"
            - name: DP_CODE_FILE_STORAGE
              value: "Database"
            - name: DP_DFS_CODE_FOLDER
              value: "/dataplane/dfs-code-files/"