apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dp-ingress.yaml
  - dp-main-deployment.yaml
  - dp-python-worker-deployment.yaml
  - nats-deployment.yaml
  - postgresql-deploy.yaml
  - postgresql-storage.yaml
  - dp-code-files-storage.yaml