version: '2.4'

services:

  redis-service:
    image: redis:7.2-alpine
    command: redis-server --save "" --appendonly no
    ports:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  postgres-test:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Hello123!"
      POSTGRES_DB: "testcypress"
    # volumes:
    #   - testcypress-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      retries: 5
    # restart: always

  nats:
    image: nats:2.9-scratch
    command:
      - "--port"
      - "4222"

  mainapp-cypresstest:
    container_name: mainapp-cypresstest
    build:
      context: ./
      dockerfile: cypress/Dockerfile.main.alpine
    ports:
      - 9002:9001
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "testcypress"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_PORT: "9001"
      DP_NATS: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_CLEANTASKS_DAYS: "60"
      DP_REMOVELOGS_DAYS: "60"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"
    healthcheck:
      test: "curl -f localhost:9001/healthz"
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      - redis-service
      - postgres-test
      - nats
      

  mainapp2-cypresstest:
    build:
      context: ./
      dockerfile: cypress/Dockerfile.main.alpine
    deploy:
      replicas: 1
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "testcypress"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_PORT: "9001"
      DP_NATS: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_CLEANTASKS_DAYS: "60"
      DP_REMOVELOGS_DAYS: "60"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"
    healthcheck:
      test: "curl -f localhost:9001/healthz"
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      - redis-service
      - postgres-test
      - nats

  dataplane-worker-cypresstest:
    build:
      context: ./
      dockerfile: cypress/Dockerfile.workerpython.debian
    # mem_limit: 512MB
    # cpus: 1.5
    deploy:
      replicas: 2
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "testcypress"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_NATS: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_1"
      DP_WORKER_CMD: "/bin/sh"
      DP_WORKER_TYPE: "vm"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Development"
      DP_WORKER_PORT: "9005"
      DP_WORKER_LANGUAGES: "Python"
      DP_WORKER_LOAD_PACKAGES: "Python"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"
    depends_on:
      - redis-service
      - postgres-test
      - nats
      - mainapp-cypresstest

  dataplane-worker-cypresstest-prod:
    build:
      context: ./
      dockerfile: cypress/Dockerfile.workerpython.debian
    # mem_limit: 512MB
    # cpus: 1.5
    deploy:
      replicas: 2
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "testcypress"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_NATS: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_1"
      DP_WORKER_CMD: "/bin/sh"
      DP_WORKER_TYPE: "vm"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Production"
      DP_WORKER_PORT: "9005"
      DP_WORKER_LANGUAGES: "Python"
      DP_WORKER_LOAD_PACKAGES: "Python"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"
    depends_on:
      - redis-service
      - postgres-test
      - nats
      - mainapp-cypresstest

