version: '3'

services:
  postgres:
    image: timescale/timescaledb:2.5.1-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Hello123!"
      POSTGRES_DB: "dataplane"
    volumes:
      - dataplane-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 60s
      retries: 5
    restart: always

  mainapp:
    image: dataplane/dataplane:dev-0.0.3
    ports:
      - 9010:9010
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:9000/healthz"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      env: "quickstart"
      basepath: "/dataplane"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e9-9d44-49ad-aa4e-9c64004c8993"
      database: "timescaledb"
      dataplane_port: "9010"
      mode: "development"
      debug: "true"
      dbdebug: "false"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  dataplane-db-volume:
