version: '3'

volumes:
  node_modules:

services:
  postgres:
    image: timescale/timescaledb:2.5.1-pg14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Hello123!"
      POSTGRES_DB: "dataplane"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 60s
      retries: 5
    restart: always

  nats:
    image: nats:2.7.0-scratch
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    ports:
      - "14222:4222"
      - "18222:8222"

  nats-r:
    image: nats:2.7.0-scratch
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--routes"
      - "nats://nats:6222"
    deploy:
      replicas: 2
      
  mainapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: tail -f /dev/null
    ports:
      - 9000:9000
      # - 3000:3000
    volumes:
      - node_modules:/appdev/frontend/node_modules
      - ../:/appdev
    environment:
      env: "local"
      dataplane_code_folder: "/appdev/code-files/"
      basepath: "/dataplane"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e8-9d43-49ac-aa4d-9c64004c8992"
      secret_encryption_key: "%WKrsNJTT*gM&9iX*iXXXiXrURdK2QTB"
      database: "timescaledb"
      dataplane_port: "9000"
      dataplane_nats: "nats://nats:4222, nats://nats-r_1:4222, nats://nats-r_2:4222"
      mode: "development"
      debug: "true"
      dbdebug: "false"
      messagedebug: "true"
      worker_heartbeat_seconds: "1"
      worker_group: "python_1"
      # vm, container, kubernetes
      worker_type: "vm"
      worker_lb: "roundrobin"
      worker_env: "Development"
      dp_cleantasks_days: "60"
      dp_removelogs_days: "60"

networks:
  default:
    external: true
    name: dataplane_network
