version: '3'

volumes:
  node_modules:

services:
  postgres:
    image: timescale/timescaledb:2.5.1-pg14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Hello123!"
      POSTGRES_DB: "dataplane"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 60s
      retries: 5
    restart: always

  redis:
    image: redis:6.2.6-bullseye
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  mainapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: tail -f /dev/null
    ports:
      - 9000:9000
      # - 3000:3000
    volumes:
      - node_modules:/appdev/frontend/node_modules
      - ../:/appdev
    environment:
      env: "local"
      dataplane_code_folder: "/appdev/code-files/"
      basepath: "/dataplane"
      secret_db_host: postgres
      secret_db_user: postgres
      secret_db_pwd: "Hello123!"
      secret_db_ssl: "disable"
      secret_db_port: "5432"
      secret_db_database: "dataplane"
      secret_jwt_secret: "117943e8-9d43-49ac-aa4d-9c64004c8992"
      secret_encryption_key: "%WKrsNJTT*gM&9iX*iXXXiXrURdK2QTB"
      database: "timescaledb"
      dataplane_port: "9000"
      mode: "development"
      debug: "true"
      dbdebug: "false"
