version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Hello123!"
      POSTGRES_DB: "dataplane"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 60s
      retries: 5
    restart: always
  
  mainapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: tail -f /dev/null
    ports:
      - 9000:9000
    volumes:
      - ../:/appdev
    environment:
      env: "local"
      basepath: "/dataplane"
      secret.db_host: postgres
      secret.db_user: postgres
      secret.db_pwd: "Hello123!"
      secret.db_ssl: "disable"
      secret.db_port: "5432"
      secret.db_database: "dataplane"
      debug: "true"
      dbdebug: "true"