name: ReactBuild

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.17"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'yarn'
        # cache-dependency-path: frontend/yarn.lock
    - run: yarn add global env-cmd
    # - run: export NODE_OPTIONS=--max-old-space-size=4096
    - run: cd frontend && yarn
    - run: cd frontend && yarn build
      env:
        CI: false
    - name: Commit report
      continue-on-error: true
      run: |
        git config --global user.name 'Dataplane Actions'
        git config --global user.email 'saul-data@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git add -A
        git commit -am "Automated React build"
        git push
        # git diff --exit-code || git commit -am "Automated React build"
        # git diff --exit-code || git push
